### ISSUE TITLE
`templateUrl` matching regex not working on windows

### ISSUE THREAD

**Issue by xAt0mZ** [YashdalfTheGray/auto-ngtemplate-loader#14]
**Describe the bug**
Not working on Windows.
Regex on https://github.com/YashdalfTheGray/auto-ngtemplate-loader/blob/master/src/util.js#L4
should be modified to 
`const regEx = /(^\s*templateUrl:\s*)['"](.*)['"](,*)(\s*)$/;`
so the template url can match `templateUrl` on windows.

We recently introduced Webpack with `auto-ngtemplate-loader` and `ngtemplate-loader` to build [Portainer](github.com/portainer/portainer). It is working smoothly on our Linux CI environments, but not on Windows ones.

**Urgency**
Normal

**To Reproduce**
Release Portainer frontend (`grunt build-webapp`).
* on Linux, generated file is approximatively 1.5M.
* on Windows, generated file is approx 500K. All templates that are not specifically required are not included in webpack generated js file (so all `templateUrl` in all `_module.js` files are not evaluated and automatically required).

**Expected behavior**
The lib should detect `templateUrl` to auto require templates on Windows. 

**Environment**
 - `OS` Windows
 - `Node.js` 8.16.0
 - `webpack` 4.26.0
 - `auto-ngtemplate-loader` 1.3.0

**Comment by YashdalfTheGray** [comment]
Osnap, thanks for reporting this @xAt0mZ! I'll look at this over the weekend if that is cool and get y'all a fix. 

All I need now is a Windows computer, EC2, here I come 😀!

**Comment by YashdalfTheGray** [comment]
Rather than try to spin up a whole EC2 machine, I figured I'd let travis do some of the heavy lifting and see if I can get away with that. 

I'm hoping that [this build][0] succeeds and the package sizes are similar for all OSes. 

[0]: https://travis-ci.org/YashdalfTheGray/auto-ngtemplate-loader/builds/543277447

**Comment by YashdalfTheGray** [comment]
☝️ that build is on a branch with the fix. I also added the OSes to the travis config on `master` so I can diff the fix vs. non fix code. 

Here is the [build without the fix][0].

[0]: https://travis-ci.org/YashdalfTheGray/auto-ngtemplate-loader/builds/543278167

**Comment by YashdalfTheGray** [comment]
Aha! You can see, if you diff the build sizes for the bundles, that the Windows ones are off by a few KBs. I'm making the change now. Will release 2.0.1 tomorrow. 

The only difference between v2 and v1 is that I've dropped support for Node.js v6 in v2 which doesn't seem like it will affect you since y'all are on Node.js v8.

**Comment by YashdalfTheGray** [comment]
Just published [v2.0.1](https://www.npmjs.com/package/auto-ngtemplate-loader). You should be able to pull now with `npm install auto-ngtemplate-loader@2.0.1`.
