### ISSUE TITLE
Unable to get auto-ngtemplate-loader working

### ISSUE THREAD

**Issue by jiahuay** [YashdalfTheGray/auto-ngtemplate-loader#8]
I'm facing issue to get auto-ngtemplate-loader working. Below is my webpack config and file structure.

```
project-name
  |___src
          |___ng1-app
          |         |___admin
          |                    |______admin.route.js
          |                    |______admin.html
          |                    |______admin.module.js
          |___index.html
```

```
  module: {
    loaders: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: ['babel-loader', 'auto-ngtemplate-loader']
            },
            {
                test: /\.html$/,
                exclude: [
                     /node_modules/,
                     path.join(process.cwd(), "src/index.html"),
                ],
                use: [
                    {
                        loader: 'ngtemplate-loader',
                        options: {
                            relativeTo: 'src/'
                        }
                    },
                    {
                        loader: 'html-loader'
                    }
                ]
            }
```

After I run the npm run build, no html file is being compiled into the bundle. Any help is appreciated.

**Comment by YashdalfTheGray** [comment]
Hey @jiahuay!

I don't see anything obvious wrong except for I have a feeling that your HTML files aren't resolving to the right path but maybe they are. if you go into the examples folder in this repository, you'll be able to see [a bunch of different configurations](https://github.com/YashdalfTheGray/auto-ngtemplate-loader/tree/master/examples) I have as examples. 

Meanwhile, I'm trying to build a stack like yours so that I can see `auto-ngtemplate-loader` work in real time and debug what's going on. I should have something for you by Monday if not sooner.

**Comment by YashdalfTheGray** [comment]
@jiahuay 

I created a [testbench repo](https://github.com/YashdalfTheGray/auto-ngtemplate-loader-test) with the structure that you put down here and your webpack config. 

I can see the html going into the `$templateCache` in the built code but I can give you write access to the repo and you can modify the code because I wanna root-cause this problem for you.

**Comment by jiahuay** [comment]
@YashdalfTheGray 
Thanks for your help!
I checked your testbench repo. Seems that I don't have `index.js` that imports the module and route files. I'll try it in my repo, and let you know the result.

**Comment by jiahuay** [comment]
@YashdalfTheGray Appreciate your help. I got it working.
